#!/bin/bash
echo "Enter file name:"
read FILENAME
FILEPATH="$(find ~/ -name $FILENAME | head -n 1)"
echo The path of the file is $FILEPATH
cp -i $FILEPATH ./ 
if []
echo "copy sucess"
else
	echo "failed to copy"
fi

